### ISSUE TITLE
syncthing to secure synchronize data between *your* devices

### ISSUE THREAD

**Issue by frericksm** [NoelDeMartin/autonomous-data#2]
consider syncthing as tool to synchronize data between your devices in a secure way. An app only needs access to data on the device it is running on. syncthing ensures instant synchronization.
Use cases
* replace your cloudbased note taking app by syncthinging your note files
* replace your cloudbased passwordmanager by syncthining  your keepass file
* replace your cloudbased music app by synthinging your music files

**Comment by NoelDeMartin** [comment]
Hi there,

Syncthing sounds interesting, it's the kind of thing I think about when I look at NextCloud. But maybe more open since it works on top of an open protocol (although Nextcloud is open source as well, but I'm not sure how it works under the hood).

What do you intend by opening this issue, do you want me to add syncthing to the list of [protocols and implementations](https://noeldemartin.github.io/autonomous-data/protocols-and-implementations.html)?

**Comment by frericksm** [comment]
Yes that was my intent. Might as well has been  a comment at hackernews instead of a issue here.
i think syncthing deserves to be brought to light as a maybe somehow low level alternative to solid  and remote storage.

**Comment by NoelDeMartin** [comment]
Ok, I've added it to the list, thanks for suggesting!

Looking into this, I realized that in my opinion this doesn't completely adhere to the Autonomous Data principles. And some of the options listed before didn't either, so I've rewritten that page to clarify.

In particular, they are lacking semantics. Here's the relevant part of the text:

> In some rare occasions, users can also export and import their data. But even then, the data format will be obscure enough for non-technical users to make it unusuable. And for technical users, the data won't be compatible with other applications. So they'll have to migrate it by hand.

If I understand correctly, syncthing (and other of the protocols listed) don't contain semantics. So if I made an app to manage movies, for example, non technical users wouldn't be able to reuse that data with other applications using the same protocol. They'd be able to migrate it, which is a big win, but they'd still need technical assistance and interoperability would be unlikely out of the box.

Solid's advantage is that it has semantics built-in, so if I anyone makes an app for managing movies it's very likely that they are using the `schema:Movie` ontology and it is compatible with other applications. Without developers even knowing each other.

I know in practice this isn't happening, mainly because there aren't that many Solid apps right now. But I've already found a couple of instances where the data generated by my apps was compatible with existing services (unbeknownst to me). So I am optimistic about it in the long run, and I think this is essential to have a healthy app ecosystem as I mention in that quote.
